name: Call API Every 5 Seconds
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  # 每分钟触发一次

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API in loop
        run: |
          for i in {1..12}; do
            # 调用你的API（替换成你的curl命令）
            curl -X GET "https://api.day.app/Q44dpDyHeXk4Tv3vkTYUjE/测试测试"
            
            # 等待5秒（如果是Windows runner使用 timeout /t 5）
            sleep 5
          done
